# Generated by Django 5.2 on 2025-12-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='authlete',
            new_name='athlete',
        ),
    ]
