# Generated by Django 5.2 on 2025-12-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_rename_authlete_run_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.CharField(choices=[('IN', 'init'), ('PR', 'in_progress'), ('FN', 'finished')], default='IN', max_length=2),
        ),
    ]
