# Generated by Django 5.2 on 2025-12-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('IN', 'init'), ('PR', 'in_progress'), ('FNfinished', 'Finished')], default='IN', max_length=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.TextField(),
        ),
    ]
