# Generated by Django 5.2 on 2025-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_run_status_alter_run_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('in_progress', 'in_progress'), ('finishedfinished', 'Finished')], default='init', max_length=25),
        ),
    ]
